= Entwicklerdokumentation

== Einführung und Ziele
* Aufgabenstellung
** In diesem Projekt wird ein Portal zur Unterstützung von Flüchtlingen erstellt. 
Hilfsbereite Menschen werden in der Lage sein, Sach- und Dienstleistungsangebote für Flüchtlinge anzubieten. 
Die Flüchtlinge können auf Angebote antworten. 
Die Kommunikation zwischen Flüchtlingen und Helfenden wird ermöglicht durch Textbausteine, die abhängig von der Sprache des Lesenden übersetzt werden. 
Durch diese Textblöcke können wir eine sehr gute Übersetzung gewährleisten im Vergleich zu einer eher schlechten dynamischen Übersetzung wie z.B. Google Translator. 
Das Portal unterstützt mehrere Sprachen. 

* Qualitätsziele

** Die Webseite muss plattformunabhänigig auf allen Geräten und jedem Webbrowser funktionieren.
** Ladezeiten müssen den von ähnlichen Webseiten entsprechen, und es darf nicht deutlich mehr als üblich viel Datenvolumen verbraucht werden.
** Das Design soll schlicht und ansprechend sein.
** Die Anwendung muss leicht erweiterbar sein.
** Es muss eine gute Kommunikation zwischen Anbieter und Interessent sichergestellt werden.
** Mann muss die Sprache ändern können
 



== Randbedingungen
* Hardware-Vorgaben
** Javafähiger Server mit Internetanbindung
* Software-Vorgaben
** Foundation Framework für Desktop und Mobile Unterstützung
** Thymeleaf für Templates
** Spring, Spring+Data mit MySQL Backend, Spring+Security für verschiedene Rollen
** EclipseLink JPA
** Lombok
** ReCaptcha2
** Java-Class basierende Konfiguration
** Maven
** Git/GitHub
** JQuery + JQueryDateTimePicker von xdsoft.net (http://xdsoft.net/jqplugins/datetimepicker/)

//* Vorgaben zum Betrieb der Software

== Kontextabgrenzung
* Externe Schnittstellen
** Mail Server
** Datenbank
** Spring
** Maven
** SalesPoint

== Lösungsstrategie
//Kurzer Überblick über Ihre grundlegenden Entscheidungen und Lösungsansätze, die jeder, der mit der Architektur zu tun hat, verstanden haben sollte.
Unser Programm baut auf dem MVC-Entwurfsmuster auf. 
Wir konstruieren eine plattformübergreifende Website. 
Sie ist responsive und passt sich dynamisch an, jenachdem auf welchem Gerät die Seite geöffnet wird.
Für alle Objekte die mehrfach vorkommen, seien es Benutzer, Artikel oder Textblöcke sind Repositories angelegt, welche alle Einheiten speichert. 
Die Sprache der Website entspricht der eingestellten Sprache im Browser des Benutzers und kann darüber hinaus in der Navigationsleiste geändert werden. 
Die Seitennavigation, sowie die Suche erfolgen über eine Navigationsleiste, die sich bis oben befindet.
Wir haben uns für drei Rollen entschieden, Admin-, Helfder- und Flüchtlingrolle. 
Der Admin hat im Vergleich zu den anderen Rollen noch die Möglichkeit ALLE Angebote zu editieren und zu löschen, und Nutzer zu deaktivieren. 
Die anderen beiden Rollen haben bis jetzt die gleichen Rechte. Eine nachträgliche Änderung ist jedoch möglich.





== Bausteinsicht
* Package-Diagramme
** refugeeApp
*** .controller
*** .model
*** .utilities
*** .utilities.mail

== Entwurfsentscheidungen
* Architektur
* Verwendete Muster
** Singelton, MVC
* Persistenz
** Durch das Benutzen der JPA sind wir flexibel im Hinblick auf die Wahl der konkreten Datenbank
* Benutzeroberfläche
** Foundation, HTML5

[appendix]
== Glossar
